[package]
name = "rika"
edition = "2024"
version = "0.0.1"

[build-dependencies]
serde_json = "1.0.149"

[dependencies]
anyhow = "1.0.102"
dirs = "6.0.0"
freedesktop-desktop-entry = { version = "0.8.1", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "1.1.2"
