[launcher]
max_visible_results = 7
font_family = ""
font_size = 14
small_font_size = 13
tiny_font_size = 10

[launcher.window]
anchor = "top"
width = 580
height = 316
margin = 320

[providers.apps]
enabled = true

[providers.commands]
enabled = true
cmds = []

[providers.web_search]
enabled = true
browser_command = ""
